#!/bin/bash

readargs() {
  while [ "$#" -gt 0 ] ; do
    case "$1" in
       -c)
        if [ "$2" ] ; then
          commit="$2"
          shift ; shift
        else
          echo "Missing a value for $1."
          echo
          shift
          usage
exit
        fi
      ;;
      *)
        echo "Unknown option or argument $1."
        echo
        shift
        usage
      exit
      ;;
    esac
  done
}

#  BEGIN THE PROGRAM
readargs "$@"
shortcommit=$( echo ${commit} | cut -c 1-7)
name=python-grpc-tools
version=1.16.0

rm -rf ${name}-${shortcommit}/
rm -f ${name}-${shortcommit}.tar.gz
git clone https://github.com/grpc/grpc.git ${name}-${shortcommit}
pushd ${name}-${shortcommit}
git checkout --force "${commit}" 
git submodule init && git submodule update
echo "You are in Commit: $( git rev-parse HEAD )"
popd
tar -cvzf ${name}-${shortcommit}.tar.gz ${name}-${shortcommit}

